### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dovy** [cconstable/OCR-iOS-Example#1]
Your app looks interesting. I was wondering if you have any experience preparing images to OCR stone. I basically want to OCR grave markers and try and grab as much good data out of them as possible. Do you think I could make that happen with tesseract-ocr?

**Comment by cconstable** [comment]
I have not but you can certainly use tesseract to do that. I would first take a photo and play around with it in some image editing software and find some settings that really make the letters pop out. You'll probably need to desaturated and boost the contrast. Once I get letters that are very clear for human eyes, I would do a batch apply for the rest of the images. 

Also, if you are getting bad results, try shrinking the image size. High res photos don't always give you the best results.

**Comment by cconstable** [comment]
Let me know how it went :)
