### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by taphive** [cconstable/OCR-iOS-Example#2]
hey man, does this even work? I ran it on a few pages and It either returns nothing or just some gibberish. Do you have a sample image to demonstrate that it actually works? Thanks!

**Comment by cconstable** [comment]
Hey Asem, I'll see if I can find some of the images I used but yes it works :)

This OCR library is especially sensitive to the size of the images you provide. I would try experimenting with many sizes of the same image.

**Comment by Swarnavas** [comment]
Hey,without using these static libraries,can i use the whole third party library in Xcode? I tried,for me its giving compilation errors.Please come back.

**Comment by cconstable** [comment]
Without more details I really can't say. If you all have specific questions about anything I wrote feel free to post but I'm afraid I can't offer any assistance regarding the Tesseract OCR library.

If you're having trouble getting the app to work with your images check the Tesseract homepage: https://code.google.com/p/tesseract-ocr/
