### ISSUE TITLE
Does Not work

### ISSUE THREAD

**Issue by hhimanshu** [cconstable/OCR-iOS-Example#4]
@mstrchrstphr, I tried the way you mentioned on XCode 6.1

My setup looks like  
![screen shot 2014-12-04 at 8 00 48 pm](https://cloud.githubusercontent.com/assets/6589036/5310903/5301b3b4-7bf0-11e4-9fff-98dcf86c29ea.png)

and when I build it, I see

![screen shot 2014-12-04 at 8 00 58 pm](https://cloud.githubusercontent.com/assets/6589036/5310906/5dd098aa-7bf0-11e4-9ebd-e5a71f540750.png)

I downloaded [Tesseract-tesseract-ocr-3.02.eng.tar.gz](https://code.google.com/p/tesseract-ocr/downloads/detail?name=tesseract-ocr-3.02.eng.tar.gz&can=2&q=)

**Comment by AaronKalantarov** [comment]
Me to. Help us.

**Comment by cconstable** [comment]
@AaronKalantarov Aw man. Didn't see this issue! I'll check now and see what's up.

@hhimanshu did you ever get this working?

**Comment by hhimanshu** [comment]
@mstrchrstphr, yes it worked for me but could not do much after that
