### ISSUE TITLE
Cannot build on Xcode 8

### ISSUE THREAD

**Issue by serejahh** [cconstable/OCR-iOS-Example#7]
Hi! I'm trying to run your example, but I got errors:
![image](https://cloud.githubusercontent.com/assets/2575555/22402916/4ff1a8b4-e610-11e6-8bcf-365a06b411a4.png)
Could you help me?

**Comment by Kazutaka333** [comment]
I have the same problem too

**Comment by nightlight89** [comment]
me too

**Comment by nirav-kotecha** [comment]
same problem. please provide solution. client is waiting for this functionality

**Comment by lucianobustos** [comment]
Lol.  "Client is waiting".
Is your client not our client.
Please contribute and be thankful with the great contribution people made to this project and given to you for free.
Bests
